spring:
  redis:
    host: localhost
    port: 6379
    password: qwe123!@# # 如果设置了密码，则填写密码
    database: 0 # Redis数据库索引（默认为0）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用Lettuce时）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用Lettuce时）
        max-idle: 8 # 连接池中的最大空闲连接（使用Lettuce时）
        min-idle: 0 # 连接池中的最小空闲连接（使用Lettuce时）
  servlet:
    multipart:
      max-file-size: 100MB # 限制单个上传文件的最大大小为 10MB。如果上传的文件大小超过这个值，将会被拒绝上传。
      max-request-size: 100MB # 限制整个上传请求的最大大小为 10MB。这包括所有上传文件的大小之和。如果请求总大小超过这个值，将会被拒绝。
  security:
    user:
      name: admin # 登录用户名
      password: 123456 # 登录密码
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/weblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#=================================================================
# minio
#=================================================================
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: quanxiaoha
  secretKey: quanxiaoha
  bucketName: weblog
#=================================================================
# rocket-mq
#=================================================================
rocketmq:
  name-server: localhost:9876  # RocketMQ NameServer 地址
  producer:
    group: hot-article-producer-group  # 生产者组名
    send-message-timeout: 3000 # 消息发送超时时间，默认 3s
    retry-times-when-send-failed: 3 # 同步发送消息失败后，重试的次数
    retry-times-when-send-async-failed: 3 # 异步发送消息失败后，重试的次数
    max-message-size: 4096 # 消息最大大小（单位：字节）
  consumer:
    group: hot-article-consumer-group  # 消费者组名

